@host = http://localhost:31979
@issueId = 7769e5f7-8b3c-4832-9272-ea9ba79d3ca3

## GET api/issues
GET {{host}}/api/issues

## GET api/issues
GET {{host}}/api/issues?includeDeleted=true

## GET api/issues/{{issueId}}
GET {{host}}/api/issues/{{issueId}}


## POST api/issues
POST {{host}}/api/issues
Content-Type: application/json

{
  "title": "test",
  "markdownBody": "one two",
  "tags": [
    "test",
    "abc-123"
  ]
}

## PATCH api/issues/{{issueId}}
PATCH {{host}}/api/issues/{{issueId}}
Content-Type: application/json

{
  "title": "hola world!",
  "markdownBody": "fixed this one",
  "tags": [
    "test",
    "fixed"
  ]
}

# DELETE api/issues/{issueId}
DELETE {{host}}/api/issues/{{issueId}}
Content-Type: application/json

# POST api/issues/{issueId}/tags
POST {{host}}/api/issues/{{issueId}}/tags
Content-Type: application/json

{
    "tags": [
        "new-tag",
        "another-tag"
    ]
}

# DELETE api/issues/{issueId}/tags/{tag}
@tag = new-tag
DELETE {{host}}/api/issues/{{issueId}}/tags/{{tag}}
Content-Type: application/json
